### ISSUE TITLE
Use a config file to store umons ID and password

### ISSUE THREAD

**Issue by Harbiinger** [Exter007/MyUMonsSchedule#2]
Using a config file should be a pretty good idea since it will be easier for the end user to set it up instead of editing the python code. And if we setup a docker version of the project it will be much much simple to use a config file external to the code.

**Comment by Exter007** [comment]
Hello Harbiinger,

I think you've a good idea. I don't know if docker is a good choice for this project (but we can test if you want ;) ).
Furthermore, I'm working on a new version which includes :

- Temporary file instead of the "screenshot.png".
- Creating a generic email which will send emails instead of using your own Gmail address.
- Creating a cron job on an alwaysdata server which will send emails automatically every day for example.

On a next next version...
I want to create a website where you can register (with your UMons address) to automate the all procees (with this version, everyone that have an internet connection and an UMons address can receive his schedule by mail ! ;) )

Let me know if you want to use Docker, I really want to see this in action !
